ruleta:
    pattern:  /
    defaults: { _controller: "gemaBundle:Ruleta:index" }

ruleta_show:
    pattern:  /{id}/show
    defaults: { _controller: "gemaBundle:Ruleta:show" }

ruleta_new:
    pattern:  /new
    defaults: { _controller: "gemaBundle:Ruleta:new" }

ruleta_create:
    pattern:  /create
    defaults: { _controller: "gemaBundle:Ruleta:create" }
    requirements: { _method: post }

ruleta_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "gemaBundle:Ruleta:edit" }

ruleta_update:
    pattern:  /{id}/update
    defaults: { _controller: "gemaBundle:Ruleta:update" }

ruleta_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "gemaBundle:Ruleta:delete" }
