<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComportamientoAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComportamientoAccionRepository extends EntityRepository
{
}
