<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * CondicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionRepository extends EntityRepository
{


    public function condicionByNombre($nombre){
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("C")
            ->from($this->getClassName(), "C")
            ->Where("C.nombre='".$nombre."'");
print($qb->getDQL());die();
        return $qb->getQuery()->getSingleResult();

    }

}
