<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * MediaDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaDescriptionRepository extends EntityRepository
{


    public function findMy($nombre,$folder,$subfolder) {
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("A")
            ->from($this->getClassName(), "A")
            ->where("A.nombre='".$nombre."'")
            ->andwhere("A.folder='".$folder."'")
            ->andwhere("A.subforlder='".$subfolder."'");
        $qb->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

}
