<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * ColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaLaboralRepository extends EntityRepository
{
    public function listarDQL() {

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->addSelect('T')
            ->from($this->getClassName(), 'T')

        ;
        return $qb;
    }


    public function filtrar(Request $request) {
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("T")
            ->from($this->getClassName(), "T")


        ;


        if ($request->request->get("searchPhrase") != null) {
            $search = $request->request->get("searchPhrase");
            $qb->where($qb->expr()->like("T.titulo", $qb->expr()->literal("%" . $search . "%")));
//            $qb->orwhere($qb->expr()->like("T.activa", $qb->expr()->literal("%" . $search . "%")))




        }
        if ($request->request->get("sort") != null) {
            $orden = $request->request->get("sort");
            // print_r($orden);die();
            foreach ($orden as $key => $value) {
                $qb->orderBy("T." . $key, $value);
            }
        }
        return $qb;
    }
}
