<?php
namespace GEMA\gemaBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * PedidobaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidobaseRepository extends EntityRepository
{
    public function listarDQL() {

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->addSelect('U')
            ->from($this->getClassName(), 'U')
            ->leftJoin("U.toro", "F");
        return $qb;
    }

    public function filtrar(Request $request) {
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("B","F")
            ->from($this->getClassName(), "B")
            ->leftJoin("B.toro", "F");


        if ($request->request->get("searchPhrase") != null) {
            $search = $request->request->get("searchPhrase");            
            $qb->where($qb->expr()->like("F.apodo", $qb->expr()->literal("%" . $search . "%")));

        }
        if ($request->request->get("sort") != null) {
            $orden = $request->request->get("sort");
            foreach ($orden as $key => $value) {
                $qb->orderBy("F.apodo" . $key, $value);
            }
        }
        return $qb;
    }


    public function findVisible(){
        
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->addSelect('U')
            ->from($this->getClassName(), 'U')
            ->leftJoin("U.toro", "F")
            ->where('U.ocultar=false')
            ->orwhere('U.ocultar is null');
        return $qb->getquery()->getResult();
    }
}
