<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * VendedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendedorRepository extends EntityRepository
{
    public function listarDQL() {

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->addSelect('U')
            ->from($this->getClassName(), 'U');
        return $qb;
    }

    public function filtrar(Request $request) {
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("B")
            ->from($this->getClassName(), "B");



        if ($request->request->get("searchPhrase") != null) {
            $search = $request->request->get("searchPhrase");
            $qb->where($qb->expr()->like("B.nombre", $qb->expr()->literal("%" . $search . "%")));

        }
        if ($request->request->get("sort") != null) {
            $orden = $request->request->get("sort");
            foreach ($orden as $key => $value) {
                $qb->orderBy("B.id" . $key, $value);
            }
        }
        return $qb;
    }

    public function findByNombProv($nombre,$idprovincia){


        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("V","P")
            ->from($this->getClassName(), "V")

            ->leftJoin('V.provincia', "P")
            ->Where("V.publico=1")
            ->andWhere("V.nombre='".$nombre."'")
            ->andWhere('P.id='.$idprovincia)
            ;
        return $qb->getQuery()->getResult()[0];

    }

    public function findByProvOrder($idprovincia){


        $qb = new QueryBuilder($this->getEntityManager());
        $qb
            ->select("V","P")
            ->from($this->getClassName(), "V")

            ->leftJoin('V.provincia', "P")
            ->Where("V.publico=1")
            ->andWhere('P.id='.$idprovincia)
            ->orderBy('V.posicion','asc')
        ;
        return $qb->getQuery()->getResult();

    }
}
