gema_admin_deptotecnico:
    resource: "@gemaBundle/Resources/config/routing/deptotecnico.yml"
    prefix:   /admin/deptotecnico

gema_admin_categorianoticia:
    resource: "@gemaBundle/Resources/config/routing/categorianoticia.yml"
    prefix:   /admin/categorianoticia

gema_admin_mediadescription:
    resource: "@gemaBundle/Resources/config/routing/mediadescription.yml"
    prefix:   /admin/mediadescription

gema_admin_configuracion:
    resource: "@gemaBundle/Resources/config/routing/configuracion.yml"
    prefix:   /admin/configuracion

gema_admin_razafather:
    resource: "@gemaBundle/Resources/config/routing/razafather.yml"
    prefix:   /admin/razafather

gema_admin_correo:
    resource: "@gemaBundle/Resources/config/routing/correo.yml"
    prefix:   /admin/correo

gema_admin_productosprogramas:
    resource: "@gemaBundle/Resources/config/routing/productosprogramas.yml"
    prefix:   /admin/productosprogramas

gema_admin_singlehtml:
    resource: "@gemaBundle/Resources/config/routing/singlehtml.yml"
    prefix:   /admin/singlehtml

gema_admin_distribuidorlocal:
    resource: "@gemaBundle/Resources/config/routing/distribuidorlocal.yml"
    prefix:   /admin/distribuidorlocal

gema_admin_vendedor:
    resource: "@gemaBundle/Resources/config/routing/vendedor.yml"
    prefix:   /admin/vendedor

gema_admin_staff:
    resource: "@gemaBundle/Resources/config/routing/staff.yml"
    prefix:   /admin/staff

gema_admin_youtube:
    resource: "@gemaBundle/Resources/config/routing/youtube.yml"
    prefix:   /admin/youtube

gema_admin_noticias:
    resource: "@gemaBundle/Resources/config/routing/noticia.yml"
    prefix:   /admin/noticias

gema_admin_distribuidor:
    resource: "@gemaBundle/Resources/config/routing/distribuidor.yml"
    prefix:   /admin/distribuidor

gema_admin_toro_:
    resource: "@gemaBundle/Resources/config/routing/toro.yml"
    prefix:   /admin/toro/

gema_admin_raza:
    resource: "@gemaBundle/Resources/config/routing/raza.yml"
    prefix:   /admin/raza

gema_admin_decorador:
    resource: "@gemaBundle/Resources/config/routing/decorador.yml"
    prefix:   /admin/decorador


gema_loggedcheck:
    pattern:  /loggedcheck
    defaults: { _controller: gemaBundle:Default:loggedcheck }
    
gema_home:
    pattern:  /
    defaults: { _controller: gemaBundle:Default:index }

gema_login:
    pattern:  login
    defaults: { _controller: gemaBundle:Seguridad:login }
    
gema_logout:
    pattern:  admin/logout
    defaults: { _controller: gemaBundle:Seguridad:logout }
    
gema_login_check:
    pattern:  admin/login_check
    defaults: { _controller: gemaBundle:Seguridad:securityCheck }
    
gemaBundle_usuario:
    resource: "@gemaBundle/Resources/config/routing/usuario.yml"
    prefix:   admin/usuario
    
gemaBundle_rol:
    resource: "@gemaBundle/Resources/config/routing/rol.yml"
    prefix:   admin/rol

gemaBundle_traza:
    resource: "@gemaBundle/Resources/config/routing/traza.yml"
    prefix:   admin/traza

gemaBundle_pagina:
    resource: "@gemaBundle/Resources/config/routing/pagina.yml"
    prefix:   /pagina

gemaBundle_adminhome:
    pattern:  /admin/
    defaults: { _controller: gemaBundle:Default:index }

gema_boletin:
    resource: "@gemaBundle/Resources/config/routing/boletin.yml"
    prefix:   admin/boletin

gema_library:
 pattern:  /{param}/{folder}/admin/library
 defaults: { _controller: "gemaBundle:Library:LibraryPage" }

gema_findfile:
 pattern:  /{texto}/findfile
 defaults: { _controller: "gemaBundle:Library:FindFile" }

gema_pushfile:
 pattern:  /{param}/{guidParam}/admin/pushfile
 defaults: { _controller: "gemaBundle:Library:CopyFile" }

gema_deletefile:
 pattern:  /{folder}/{guidParam}/{filename}/admin/deletefile
 defaults: { _controller: "gemaBundle:Library:DeleteFile" }

gema_filesurl:
 pattern:  /{param}/{folder}/admin/filesurl
 defaults: { _controller: "gemaBundle:Library:LibraryPage" }

gema_admin_tiporaza:
    resource: "@gemaBundle/Resources/config/routing/tiporaza.yml"
    prefix: admin/tiporaza

gema_admin_uploadexcel:
    pattern:  admin/uploadexcel
    defaults: { _controller: gemaBundle:Uploader:upload }

gema_admin_distribuidor:
    resource: "@gemaBundle/Resources/config/routing/distribuidor.yml"
    prefix: admin/distribuidor

gema_razalist:
    pattern:  /toros/{nombre}
    defaults: { _controller: "gemaBundle:Razalist:listRaza" }

gema_torodetail:
    pattern:  /toro/{apodo}
    defaults: { _controller: "gemaBundle:Razalist:toroDetail" }

gema_raza_tablas:
    pattern:  /{id}/tablabyraza
    defaults: { _controller: "gemaBundle:Uploader:findTablasByRaza" }

gema_searchtoroscarne:
    pattern:  /{dato}/{isfull}/busquedacarne
    defaults: { _controller: "gemaBundle:Razalist:searchCarne" }

gema_datosoficina:
    resource: "@gemaBundle/Resources/config/routing/datosoficina.yml"
    prefix:   admin/datosoficina

gema_redventas:
    pattern:  /redventas/{codigo}
    defaults: { _controller: "gemaBundle:Redventas:inicio" }

gema_mixed:
    pattern:  admin/vendedores/{idprovincia}
    defaults: { _controller: "gemaBundle:Staff:mixed" }

gema_searchtoroscarnelike:
    pattern:  /{dato}/busquedacarnelike
    defaults: { _controller: "gemaBundle:Razalist:searchcarnev2" }

gema_clientnews:
    pattern:  /{tipo}/{start}/{end}/news
    defaults: { _controller: "gemaBundle:Clientnews:clientnoticias" }

gema_clientsinglenews:
    pattern:  /{id}/new
    defaults: { _controller: "gemaBundle:Clientnews:clientsinflenoticia" }

gema_clientsboletines:
    pattern:  /{start}/{end}/boletines
    defaults: { _controller: "gemaBundle:Clientnews:clienlistboletines" }

gema_clientboletin:
    pattern:  /{id}/clientboletin
    defaults: { _controller: "gemaBundle:Clientnews:clientboletin" }

gema_clientcontenido:
    pattern:  /{nombre}/contenido
    defaults: { _controller: "gemaBundle:Singlehtmlclient:gethtml" }

gema_prodprog:
    pattern:  /productosprogramas
    defaults: { _controller: "gemaBundle:ProdProgclient:index" }

gema_mailindex:
    pattern:  /contacto
    defaults: { _controller: "gemaBundle:Mail:contactindex" }

gema_sendmail:
    pattern:  /sendmail
    defaults: { _controller: "gemaBundle:Mail:sendmail" }

gema_sellermail:
    pattern:  /sellermail
    defaults: { _controller: "gemaBundle:Mail:sellermail" }

gema_export:
    pattern:  /{toros}/{alltoros}/exportar
    defaults: { _controller: "gemaBundle:Export:excelExport" }

gema_toropdf:
    pattern:  /{toroId}/pdf
    defaults: { _controller: "gemaBundle:Export:todopdf" }

gema_setmediadescription:
    pattern:  /{folder}/{subfolder}/{nombre}/{description}/desc
    defaults: { _controller: "gemaBundle:Library:setdescription" }

gema_getmediadescription:
    pattern:  /{folder}/{subfolder}/{nombre}/getdesc
    defaults: { _controller: "gemaBundle:Library:getdescription" }

gema_torocambpublic:
    pattern:  /{id}/cpc
    defaults: { _controller: "gemaBundle:Toro:changepublic" }